DROP DATABASE IF EXISTS nycflights;
CREATE DATABASE nycflights;
CREATE USER IF NOT EXISTS 'travis'@'%'; GRANT ALL ON *.* TO 'travis'@'%';
FLUSH PRIVILEGES;
ALTER USER 'travis'@'%' IDENTIFIED BY '';
FLUSH PRIVILEGES;

